import { mkdirSync, writeFileSync } from 'node:fs';
import { CITY_CONFIG } from '../src/config/cities.js';
import { normalizeName } from '../src/geo/normalize.js';
import { CITIES, type City, type GazetteerEntry } from '../src/types.js';

const OVERPASS = 'https://overpass-api.de/api/interpreter';
const UA = 'Safeit/0.1 (+https://github.com/Y5Yash/Safeit)';
const OUT = new URL('../src/geo/gazetteer-data/', import.meta.url);
const MAX_ATTEMPTS = 4;
const RETRY_WAIT_MS = 60_000;

interface El { lat?: number; lon?: number; center?: { lat: number; lon: number }; tags?: Record<string, string> }

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function overpass(city: City, q: string): Promise<El[]> {
  for (let attempt = 1; ; attempt++) {
    let status = 0;
    try {
      const res = await fetch(OVERPASS, {
        method: 'POST', body: new URLSearchParams({ data: q }), headers: { 'user-agent': UA },
      });
      if (res.ok) return ((await res.json()) as { elements: El[] }).elements;
      status = res.status;
      if (![429, 502, 503, 504].includes(status)) throw new Error(`overpass ${city}: HTTP ${status}`);
    } catch (e) {
      if (status === 0 && attempt >= MAX_ATTEMPTS) throw e;
      if (status !== 0 && ![429, 502, 503, 504].includes(status)) throw e;
    }
    if (attempt >= MAX_ATTEMPTS) throw new Error(`overpass ${city}: HTTP ${status} after ${attempt} attempts`);
    console.warn(`overpass ${city}: ${status || 'network error'}, retrying in ${RETRY_WAIT_MS / 1000}s (attempt ${attempt})`);
    await sleep(RETRY_WAIT_MS);
  }
}

async function fetchCity(city: City): Promise<GazetteerEntry[]> {
  const { minLat, minLng, maxLat, maxLng } = CITY_CONFIG[city].bbox;
  const bb = `${minLat},${minLng},${maxLat},${maxLng}`;
  const q = `[out:json][timeout:180];(
    nwr["amenity"="police"]["name"](${bb});
    node["place"~"^(suburb|neighbourhood|quarter|locality|village|town|hamlet)$"]["name"](${bb});
  );out center tags;`;
  const elements = await overpass(city, q);
  const seen = new Set<string>();
  const out: GazetteerEntry[] = [];
  for (const el of elements) {
    const t = el.tags ?? {};
    const name = t['name:en'] ?? t.name;
    const lat = el.lat ?? el.center?.lat;
    const lng = el.lon ?? el.center?.lon;
    if (!name || lat === undefined || lng === undefined || !/^[\x20-\x7E]+$/.test(name)) continue;
    const kind = t.amenity === 'police' ? 'police_station' : 'locality';
    const key = `${kind}|${normalizeName(name)}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push({ name, kind, lat: Math.round(lat * 1e5) / 1e5, lng: Math.round(lng * 1e5) / 1e5 });
  }
  return out;
}

async function main() {
  mkdirSync(OUT, { recursive: true });
  for (const city of CITIES) {
    const entries = await fetchCity(city);
    writeFileSync(new URL(`${city}.ts`, OUT),
      `import type { GazetteerEntry } from '../../types.js';\n\n// Generated by scripts/seed-gazetteer.ts from OpenStreetMap (ODbL). Do not edit.\nconst data: GazetteerEntry[] = ${JSON.stringify(entries)};\n\nexport default data;\n`);
    console.log(`${city}: ${entries.length} entries (${entries.filter((e) => e.kind === 'police_station').length} police stations)`);
    await sleep(5000);
  }
  writeFileSync(new URL('index.ts', OUT),
    `import type { City, GazetteerEntry } from '../../types.js';\nimport bengaluru from './bengaluru.js';\nimport delhi from './delhi.js';\nimport goa from './goa.js';\n\nexport const GAZETTEER: Record<City, GazetteerEntry[]> = { delhi, bengaluru, goa };\n`);
}

main().catch((e) => { console.error(e); process.exit(1); });
